[package]
name = "ritellm"
version = "0.1.7"
edition = "2021"

[lib]
name = "ritellm"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module", "abi3-py38"] }
reqwest = { version = "0.12.24", features = ["json", "rustls-tls", "stream"], default-features = false }
serde_json = "1.0.145"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.40", features = ["rt-multi-thread", "macros"] }
futures-util = "0.3"
pyo3-asyncio = { version = "0.20.0", features = ["tokio-runtime"] }
